# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f1d181f3876939532685363e7e0e76ab3c7980ea5814bede45fe31f113b781d3f4bc7eb9a08cee07fc8a03ddda92063c0d796be206211105e1ed4aed55d93c09

test:
  secret_key_base: 20f932d6907f2591bdb4d9a04921c18258f9f856614ea6973bf8cc23d63aea83e47d953e581662138f7df784d7b662a3494d4218885d7ec88e03a0e0fb5172f3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
